[package]
name = 'token-vesting'
version = '1.0.0'

[addresses]
token_vesting = "0xd609a293c91b549bed9b8d624f14c92ef99ef64bb2871051a6fe8dade9fdd048"

[dependencies]
AptosFramework = { local = "/Users/evilboyajay/aptos-core/aptos-move/framework/aptos-framework" }